### ISSUE TITLE
Looking for GraphQL FE/BE resources

### ISSUE THREAD

**Issue by GreysonElkins** [michaeljevans/Crate#21]
And sharing them here!

**Comment by NakiNorton** [comment]
The GraphQL documentation is really useful and easy to follow: https://graphql.org/learn/

### Misc notes:
A GraphQL service is created by defining types and fields on those types, then providing functions for each field on each type.

GraphQL APIs are organized in terms of types and fields, not endpoints. Access the full capabilities of your data from a single endpoint.

A received query is first checked to ensure it only refers to the types and fields defined, then runs the provided functions to produce a result.

Every GraphQL service has a query type and may or may not have a mutation type. These types are the same as a regular object type, but they are special because they define the entry point of every GraphQL query. 

Here's a good resource about the GraphQL type system and how it describes what data can be queried. https://graphql.org/learn/schema/

### Main Concepts:
* **Fields** - GraphQL is about asking for specific fields (properties) on objects. GraphQL queries can traverse related objects and their fields, so you can fetch lots of related data in one request, instead of making several roundtrips as one would need in a classic REST architecture.
* **Arguments** - You can pass arguments to fields. Every field and nested object can get its own set of arguments. This enables us to request specific data I.e. human(id: "1000") requesting the human with id of 1000. (In a system like REST, you can only pass a single set of arguments - the query parameters and URL segments in your request).
* **Aliases** - since the result object fields match the name of the field in the query but don't include arguments, you can't directly query for the same field with different arguments. That's why you need aliases - they let you rename the result of a field to anything you want.
* **Fragments** - GraphQL includes reusable units called fragments. Fragments let you construct sets of fields, and then include them in queries where you need to.
* **Variables** - When we start working with variables, we need to do three things:
1. Replace the static value in the query with $variableName
2. Declare $variableName as one of the variables accepted by the query
3. Pass variableName: value in the separate, transport-specific (usually JSON) variables dictionary
Default values can also be assigned to the variables in the query by adding the default value after the type declaration. I.e. 

```
query HeroNameAndFriends($episode: Episode = JEDI) {
  hero(episode: $episode) {
    name
    friends {
      name
    }
  }
}

```
When default values are provided for all variables, you can call the query without passing any variables. If any variables are passed as part of the variables dictionary, they will override the defaults.

* **Directives** -  A directive is a new feature in GraphQL. A directive can be attached to a field or fragment inclusion, and can affect execution of the query in any way the server desires. The core GraphQL specification includes exactly two directives, which must be supported by any spec-compliant GraphQL server implementation:    
@include(if: Boolean) Only include this field in the result if the argument is true.    
 @skip(if: Boolean) Skip this field if the argument is true.    

Directives can be useful to get out of situations where you otherwise would need to do string manipulation to add and remove fields in your query. Server implementations may also add experimental features by defining completely new directives.

* **Operation name and type**: Here we have the keyword _query_ as **operation type** and _HeroNameAndFriends_ as **operation name** :

 ```
query HeroNameAndFriends {
  hero {
    name
    friends {
      name
    }
  }
}
```

The **operation type** is either query, mutation, (or subscription) and describes what type of operation you're intending to do. The **operation type** is required unless you're using the query shorthand syntax, in which case you can't supply a name or variable definitions for your operation.

The **operation name** is a meaningful and explicit name for your operation (usually optional, but it’s helpful to include for developer empathy and debugging. It’s like the equivalent of a function name in JS.

### Mutations
Most discussions of GraphQL focus on data fetching, but any complete data platform needs a way to modify server-side data as well.

In REST, any request might end up causing some side-effects on the server, but by convention it's suggested that one doesn't use GET requests to modify data. 

GraphQL is similar - technically any query could be implemented to cause a data write. However, it's useful to establish a convention that **any operations that cause writes should be sent explicitly via a mutation.**

Just like in queries, if the mutation field returns an object type, you can ask for nested fields. This can be useful for fetching the new state of an object after an update.
